version: 2
updates:
  # Gradle dependencies
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    target-branch: "main"
    labels:
      - "dependencies"
      - "gradle"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    ignore:
      # Ignore patch updates for stable dependencies
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    groups:
      # Group all kotlin related updates together
      kotlin-ecosystem:
        patterns:
          - "org.jetbrains.kotlin*"
          - "com.pinterest.ktlint"
          - "io.gitlab.arturbosch.detekt"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
