repos:
  # Standard pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=36000]
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-json
      - id: check-yaml
      - id: check-xml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: no-commit-to-branch
        args: ["--branch", "main"]
      - id: detect-private-key

  - repo: https://github.com/jlleitschuh/ktlint-gradle
    rev: 12.1.0
    hooks:
      - id: ktlint
        args: [--android, --relative, --reporter=plain, --reporter=sarif]
        additional_dependencies: ["com.pinterest.ktlint:ktlint-cli:1.1.1"]

  - repo: https://github.com/detekt/detekt
    rev: v1.23.5
    hooks:
      - id: detekt
        args: [--config, config/detekt.yml, --baseline, config/baseline.xml]

  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.18.2
    hooks:
      - id: gitleaks
        args: [protect, --verbose, --redact, --staged]

  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.12.0
    hooks:
      - id: pretty-format-kotlin
        args: [--autofix]

  - repo: https://github.com/rhysd/actionlint
    rev: 5db9d9cde2f3deb5035dea3e45f0a9fff2f29448
    hooks:
      - id: actionlint
        name: Check Github Actions

  - repo: https://github.com/Yelp/detect-secrets
    rev: 01886c8a910c64595c47f186ca1ffc0b77fa5458
    hooks:
      - id: detect-secrets

  - repo: local
    hooks:
      - id: gradle-check
        name: gradle check
        entry: ./gradlew
        args: [check]
        language: system
        pass_filenames: false
        types: [kotlin]

      - id: gradle-test
        name: gradle test
        entry: ./gradlew
        args: [test]
        language: system
        pass_filenames: false
        types: [kotlin]
        stages: [push]

      - id: spotbugs
        name: spotbugs
        entry: ./gradlew
        args: [spotbugsMain]
        language: system
        pass_filenames: false
        types: [kotlin, java]

      - id: check-github-actions
        name: Check GitHub Actions for Pinned Dependencies
        entry: python .scripts/check_pinned_hash_dependencies.py
        language: python
        files: \.github/.*\.yml$
