complexity:
  LongParameterList:
    functionThreshold: 6
    constructorThreshold: 7
  TooManyFunctions:
    thresholdInFiles: 11
    thresholdInClasses: 11
    thresholdInInterfaces: 11
    thresholdInObjects: 11

style:
  MaxLineLength:
    maxLineLength: 120
  MagicNumber:
    active: true
    ignoreNumbers: ["-1", "0", "1", "2"]
    ignoreHashCodeFunction: true
    ignorePropertyDeclaration: false
    ignoreConstantDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
    ignoreAnnotation: false
    ignoreNamedArgument: true
    ignoreEnums: false
    ignoreRanges: false
  ReturnCount:
    max: 3
  NewLineAtEndOfFile:
    active: true
  WildcardImport:
    active: true

formatting:
  active: true
  android: false
  autoCorrect: true

  AnnotationOnSeparateLine:
    active: true
    autoCorrect: true

  Indentation:
    active: true
    autoCorrect: true
    indentSize: 4

naming:
  active: true
  ClassNaming:
    classPattern: "[A-Z][a-zA-Z0-9]*"
  ConstructorParameterNaming:
    parameterPattern: "[a-z][A-Za-z0-9]*"
  FunctionNaming:
    functionPattern: "[a-z][a-zA-Z0-9]*"
  TopLevelPropertyNaming:
    constantPattern: "[A-Z][A-Z0-9]*(_[A-Z0-9]+)*"
    propertyPattern: "[A-Za-z][_A-Za-z0-9]*"
    privatePropertyPattern: "_?[A-Za-z][_A-Za-z0-9]*"
