build:
  maxIssues: 0
  weights:
    complexity: 2
    style: 1

complexity:
  LongMethod:
    threshold: 130 # Increased from 120 to accommodate provideMenuItems
    excludes: ["**/StickyBurpContextMenu.kt"] # Exclude this file from LongMethod check
  LongParameterList:
    functionThreshold: 5
    constructorThreshold: 6
  TooManyFunctions:
    thresholdInFiles: 15
    thresholdInClasses: 15 # Increased to accommodate StickyBurpTab
    thresholdInInterfaces: 8
    thresholdInObjects: 8
  CyclomaticComplexMethod:
    threshold: 20 # Increased to accommodate provideMenuItems
    excludes: ["**/StickyBurpContextMenu.kt"] # Exclude this file from complexity check

exceptions:
  TooGenericExceptionCaught:
    active: false # Disabled to catch exceptions
  ExceptionRaisedInUnexpectedLocation:
    active: true
  PrintStackTrace:
    active: true
  ThrowingExceptionsWithoutMessageOrCause:
    active: true
  SwallowedException:
    active: false # Disabled for empty catch blocks

style:
  MaxLineLength:
    maxLineLength: 150
  MagicNumber:
    active: true
    ignoreNumbers:
      [
        "-1",
        "0",
        "1",
        "2",
        "3",
        "4",
        "5",
        "10",
        "24",
        "32",
        "38",
        "41",
        "54",
        "76",
        "79",
        "81",
        "84",
        "86",
        "89",
      ]
    ignoreHashCodeFunction: true
    ignorePropertyDeclaration: false
    ignoreConstantDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
    ignoreAnnotation: false
    ignoreNamedArgument: true
    ignoreEnums: false
    ignoreRanges: false
    excludes: ["**/StickyBurpTab.kt"] # Exclude StickyBurpTab.kt entirely from magic number checks
  ReturnCount:
    max: 6 # Increased to accommodate addNewVariable
  NewLineAtEndOfFile:
    active: false # Disable newline at end of file check completely
  WildcardImport:
    active: false # Disabled to allow wildcard imports extensively
  UnnecessaryAbstractClass:
    active: true
  UnusedPrivateMember:
    active: true

naming:
  active: true
  ClassNaming:
    classPattern: "[A-Z][a-zA-Z0-9]*"
  ConstructorParameterNaming:
    parameterPattern: "[a-z][A-Za-z0-9]*"
  FunctionNaming:
    functionPattern: "[a-z][a-zA-Z0-9]*"
  TopLevelPropertyNaming:
    constantPattern: "[A-Z][A-Z0-9]*(_[A-Z0-9]+)*"
    propertyPattern: "[A-Za-z][_A-Za-z0-9]*"
    privatePropertyPattern: "_?[A-Za-z][_A-Za-z0-9]*"

comments:
  active: true
  excludes: ["**/test/**", "**/androidTest/**", "**/jvmTest/**"]
  CommentOverPrivateFunction:
    active: true
  CommentOverPrivateProperty:
    active: true

potential-bugs:
  Deprecation:
    active: true
  EqualsAlwaysReturnsTrueOrFalse:
    active: true
  UnconditionalJumpStatementInLoop:
    active: true

empty-blocks:
  EmptyCatchBlock:
    active: true
    allowedExceptionNameRegex: "^(_|(ignore|expected).*)"
