build:
  maxIssues: 0
  weights:
    complexity: 2
    style: 1

complexity:
  LongParameterList:
    functionThreshold: 5
    constructorThreshold: 6
  TooManyFunctions:
    thresholdInFiles: 10
    thresholdInClasses: 10
    thresholdInInterfaces: 8
    thresholdInObjects: 8
  CyclomaticComplexMethod:
    threshold: 10

exceptions:
  TooGenericExceptionCaught:
    active: true
  ExceptionRaisedInUnexpectedLocation:
    active: true
  PrintStackTrace:
    active: true
  ThrowingExceptionsWithoutMessageOrCause:
    active: true

style:
  MaxLineLength:
    maxLineLength: 120
  MagicNumber:
    active: true
    ignoreNumbers: ["-1", "0", "1", "2"]
    ignoreHashCodeFunction: true
    ignorePropertyDeclaration: false
    ignoreConstantDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
    ignoreAnnotation: false
    ignoreNamedArgument: true
    ignoreEnums: false
    ignoreRanges: false
  ReturnCount:
    max: 3
  NewLineAtEndOfFile:
    active: true
  WildcardImport:
    active: true
  UnnecessaryAbstractClass:
    active: true
  UnusedPrivateMember:
    active: true

naming:
  active: true
  ClassNaming:
    classPattern: "[A-Z][a-zA-Z0-9]*"
  ConstructorParameterNaming:
    parameterPattern: "[a-z][A-Za-z0-9]*"
  FunctionNaming:
    functionPattern: "[a-z][a-zA-Z0-9]*"
  TopLevelPropertyNaming:
    constantPattern: "[A-Z][A-Z0-9]*(_[A-Z0-9]+)*"
    propertyPattern: "[A-Za-z][_A-Za-z0-9]*"
    privatePropertyPattern: "_?[A-Za-z][_A-Za-z0-9]*"

comments:
  active: true
  excludes: ["**/test/**", "**/androidTest/**", "**/jvmTest/**"]
  CommentOverPrivateFunction:
    active: true
  CommentOverPrivateProperty:
    active: true

potential-bugs:
  Deprecation:
    active: true
  EqualsAlwaysReturnsTrueOrFalse:
    active: true
  UnconditionalJumpStatementInLoop:
    active: true
